version: "3.8"

name: microservices-demo
services:
  postgres:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - msl-postgresql:/var/lib/postgresql/data
      - ./docker/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - 5432:5432
    env_file:
      - ./docker/.env
    restart: unless-stopped
    networks:
      - spring-cloud-network


  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - msl-rabbitmq-data:/var/lib/rabbitmq/
      - msl-rabbitmq-log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    env_file:
      - ./docker/.env
    restart: unless-stopped
    networks:
      - spring-cloud-network

  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566            # LocalStack Gateway
      - 4510-4559:4510-4559  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - msl-localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/s3create.sh:/docker-entrypoint-initaws.d/init-aws.sh
    env_file:
      - ./docker/.env
    restart: unless-stopped
    networks:
      - spring-cloud-network

  resource-service:
    depends_on:
      - rabbitmq
      - postgres
      - localstack
    image: resource-service
    build:
      context: ./resource-service/
      dockerfile: Dockerfile
    ports:
      - 8071:8071
    env_file:
      - ./docker/.env
    restart: unless-stopped
    networks:
      - spring-cloud-network
    links:
      - localstack:localstack


  song-service:
    depends_on:
      - postgres
    image: song-service:latest
    build:
      context: ./song-service/
      dockerfile: Dockerfile
    env_file:
      - ./docker/.env
    ports:
      - 8070:8070
    restart: unless-stopped
    networks:
      - spring-cloud-network

  resource-processing-service:
    depends_on:
      - rabbitmq
      - postgres
    image: resource-processing-service:latest
    build:
      context: ./resource-processing-service/
      dockerfile: Dockerfile
    env_file:
      - ./docker/.env
    restart: unless-stopped
    networks:
      - spring-cloud-network
#
#  keycloak:
#    depends_on:
#      - postgres
#    container_name: keycloak
#    environment:
#      DB_VENDOR: postgres
#      DB_ADDR: ${POSTGRESQL_ADDRES}
#      DB_DATABASE: ${POSTGRESQL_DB}
#      DB_USER: ${POSTGRESQL_USER}
#      DB_PASSWORD: ${POSTGRESQL_PASS}
#      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
#      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
#    image: quay.io/keycloak/keycloak:latest
#    volumes:
#        - msl-keycloak:/opt/keycloak/data/
#    restart: unless-stopped

volumes:
  msl-localstack:
  msl-postgresql:
  msl-rabbitmq-data:
  msl-rabbitmq-log:
  msl-keycloak:

networks:
  spring-cloud-network:
    driver: bridge