processing-service:
  newResourceUploadedQueueName: resourceUploaded
  resourceProcessedQueueName: resourceProcessed

spring:
  rabbitmq:
    username: admin
    password: admin
    host: localhost
  cloud:
    config:
      name: resource-processing-service
      discovery:
        enabled: true
        service-id: config-service
  application:
    name: resource-processing-service

eureka:
  instance:
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

server:
  port: 8073
  max-http-header-size: 40KB
  servlet:
    context-path: /
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - metrics
          - info
          - health
