processing-service:
  newResourceUploadedQueueName: resourceUploaded
  songServiceRootUri: http://${SONG_SERVICE_HOST}:8070
  resourceServiceRootUri: http://${RESOURCE_SERVICE_HOST}:8071

spring:
  rabbitmq:
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    host: ${RABBIT_HOST}