processing-service:
  newResourceUploadedQueueName: resourceUploaded
  songServiceRootUri: http://127.0.0.1:8070
  resourceServiceRootUri: http://127.0.0.1:8071

spring:
  rabbitmq:
    username: admin
    password: admin
    host: localhost
  cloud:
    config:
      name: resource-processing-service
      discovery:
        enabled: true
        service-id: config-service
  application:
    name: resource-processing-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

server:
  port: 8073
  max-http-header-size: 40KB
  servlet:
    context-path: /
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto