spring:
  liquibase:
    changeLog: resource.db-changelog/resource-changelog-master.xml
  servlet:
    multipart:
      max-file-size: 35MB
      max-request-size: 35MB
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/msd_resources
    username: ${PG_RESOURCE_SERVICE_USERNAME}
    password: ${PG_RESOURCE_SERVICE_PASSWORD}
  jpa:
    show-sql: true
  rabbitmq:
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    host: ${RABBIT_HOST}

resource-service:
  s3Endpoint: http://${S3_HOST}:4566
  s3Bucket: resource-bucket
  newResourceUploadedQueueName: resourceUploaded

server:
  port: 8071
  max-http-header-size: 40KB
  servlet:
    context-path: /
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

springdoc:
  packagesToScan: com.akalji.learn.microservices.resourceservice.controller
  swagger-ui:
    docExpansion: none
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha

