spring:
  liquibase:
    changeLog: resource.db-changelog/resource-changelog-master.xml
  servlet:
    multipart:
      max-file-size: 35MB
      max-request-size: 35MB
  datasource:
    url: jdbc:postgresql://localhost:5432/msd_resources
    username: msd_resources
    password: msd_resources
  jpa:
    show-sql: true
  rabbitmq:
    username: admin
    password: admin
    host: localhost
  application:
    name: resource-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

resource-service:
  s3Endpoint: http://localhost:4566
  s3Bucket: resource-bucket
  newResourceUploadedQueueName: resourceUploaded
  resourceProcessedQueueName: resourceProcessed

server:
  port: 8071
  max-http-header-size: 40KB
  servlet:
    context-path: /
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

springdoc:
  packagesToScan: com.akalji.learn.microservices.resourceservice.controller
  swagger-ui:
    docExpansion: none
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info
logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error

resilience4j.circuitbreaker:
  instances:
    add:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpClientErrorException


